# 개요

작업 진행을 정리하는 ipython 노트북입니다.

# 파싱

원본 데이터는 반정형의 로그데이터이기 때문에 이를 정규표현식을 활용하여 파싱해서 pandas df에 저장하는 작업입니다.

파싱 코드는 빅데이터를 지탱하는 기술 책을 참조하여 작성되었습니다.

In [1]:
import re
import pandas as pd

In [2]:
path = "data/log_data/data/day01.log"

In [3]:
pattern = re.compile('(\S+) - - \[(.*)\] "(.*)" (\S+) (\S+)$')

In [4]:
def parse_access_log(path):
    for line in open(path, 'rb'):
        line = line.decode(encoding='ascii', errors='ignore')
        for m in pattern.finditer(line):
            yield m.groups()

In [5]:
columns = ["host", 'time', 'request', 'status', 'bytes']

In [6]:
log_df = pd.DataFrame(parse_access_log(path), columns = columns)

In [7]:
log_df.head()

,host,time,request,status,bytes
0,199.72.81.55,01/Jul/1995:00:00:01 -0400,GET /history/apollo/ HTTP/1.0,200,6245
1,unicomp6.unicomp.net,01/Jul/1995:00:00:06 -0400,GET /shuttle/countdown/ HTTP/1.0,200,3985
2,199.120.110.21,01/Jul/1995:00:00:09 -0400,GET /shuttle/missions/sts-73/mission-sts-73.ht...,200,4085
3,burger.letters.com,01/Jul/1995:00:00:11 -0400,GET /shuttle/countdown/liftoff.html HTTP/1.0,304,0
4,199.120.110.21,01/Jul/1995:00:00:11 -0400,GET /shuttle/missions/sts-73/sts-73-patch-smal...,200,4179

- host: 접속한 호스트 ip주소나 도메인이 나타남
- time: 접속 시간 UTC+04:00
- request: 요청, 요청 종류와 경로
- status: http 상태 코드
- bytes: 전송된 데이터의 크기

# 변환

##  Time

문자열 형태에서 datetime으로 변환

In [8]:
log_df["time"]= pd.to_datetime(log_df["time"], format='%d/%b/%Y:%X', exact=False)

dw의 스키마에서 Time table에 column으로 
day	weekday	month	year	hour	minute	second	time_key

In [9]:
log_df["day"] = log_df["time"].map(lambda x: x.day)
log_df["weekday"] = log_df["time"].map(lambda x: x.weekday())
log_df["month"] = log_df["time"].map(lambda x: x.month)
log_df["year"] = log_df["time"].map(lambda x: x.year)
log_df["hour"] = log_df["time"].map(lambda x: x.hour)
log_df["minute"] = log_df["time"].map(lambda x: x.minute)
log_df["second"] = log_df["time"].map(lambda x: x.second)

In [10]:
log_df["time_key"] = log_df.apply(lambda x: int("%04d%02d%02d%02d%02d%02d" %(x["year"], x["month"],x["day"],x["hour"],x["minute"],x["second"])), axis = 1)

In [11]:
log_df.head()

,host,time,request,status,bytes,day,weekday,month,year,hour,minute,second,time_key
0,199.72.81.55,1995-07-01 00:00:01,GET /history/apollo/ HTTP/1.0,200,6245,1,5,7,1995,0,0,1,19950701000001
1,unicomp6.unicomp.net,1995-07-01 00:00:06,GET /shuttle/countdown/ HTTP/1.0,200,3985,1,5,7,1995,0,0,6,19950701000006
2,199.120.110.21,1995-07-01 00:00:09,GET /shuttle/missions/sts-73/mission-sts-73.ht...,200,4085,1,5,7,1995,0,0,9,19950701000009
3,burger.letters.com,1995-07-01 00:00:11,GET /shuttle/countdown/liftoff.html HTTP/1.0,304,0,1,5,7,1995,0,0,11,19950701000011
4,199.120.110.21,1995-07-01 00:00:11,GET /shuttle/missions/sts-73/sts-73-patch-smal...,200,4179,1,5,7,1995,0,0,11,19950701000011

디멘션 테이블의 기본키를 인조키로 만든다고 책에 적혀 있었는데 예제들과 현업에 계신 분들께 여쭤보니 날짜+시간은 그 자체가 유일해지기 때문에 다루기 편하게 인조키를 안 쓰고 시간을 그대로 키로 사용한다고 한다.